# Generated by Django 4.2.3 on 2023-07-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_post_like_post_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_post',
            new_name='user_like_post',
        ),
    ]
