# Generated by Django 4.2.3 on 2023-09-03 09:58

from django.db import migrations, models
import social_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_alter_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=social_app.models.get_post_image_filepath),
        ),
    ]
