# Generated by Django 4.2.3 on 2023-09-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_alter_post_image_sharedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedpost',
            name='user_like_post',
        ),
    ]
