# Generated by Django 4.2.5 on 2024-07-10 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_app', '0007_remove_post_posted_by_post_reposted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_users',
            field=models.ManyToManyField(blank=True, related_name='users_repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
