# Generated by Django 4.2.5 on 2024-04-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_groups', '0002_publicroomchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
